### ISSUE TITLE
[v0.1.20/py2.7] SyntaxError: 'return' with argument inside generator

### ISSUE THREAD

**Issue by jschueller** [asweigart/pyscreeze#46]
Latest version 0.1.20 throws on import with python 2.7:
```
python -c 'import pyautogui'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$PREFIX/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "$PREFIX/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator
```

**Comment by bevar3** [comment]
Hi ,
I am a beginer in using PyAutoGui and it is failing in  import pyautogui line itself. kindly assist.

Traceback (most recent call last):
  File "C:\python scripts\autogui.py", line 1, in <module>
    from  pyautogui import *
  File "build\bdist.win-amd64\egg\pyautogui\__init__.py", line 84, in <module>
  File "C:\Python27\lib\site-packages\pyscreeze-0.1.20-py2.7.egg\pyscreeze\__init__.py", line 168
SyntaxError: 'return' with argument inside generator
[Finished in 0.4s]

**Comment by brenly** [comment]
using python 3 solved my problem. i strongly encourage you to migrate to python 3 and do not look back.

**Comment by thefeiter** [comment]
I am having the same problem on Ubuntu:

File "./test.py", line 7, in <module>
    import pyautogui
  File "/home/user/.local/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/home/user/.local/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator

**Comment by bbrtan** [comment]
there are dependant library eg imagehorizon which is 2.7 hence there is a need to use this.


[ ERROR ] Error in file 'C:\Users\xxxx\auto_testing_pay\trunk\Test\Regression\01_FC324_NewHire.robot': Importing test library 'ImageHorizonLibrary' failed: SyntaxError: 'return' with argument inside generator (__init__.py, line 168)
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\ImageHorizonLibrary\__init__.py", line 8, in <module>
    import pyautogui as ag
  File "C:\Python27\Lib\site-packages\pyautogui\__init__.py", line 65, in <module>
    import pyscreeze.

some cant move to python 3 yet. will try another version

**Comment by lixxu** [comment]
maybe this can fix it: [https://stackoverflow.com/questions/15809296/python-syntaxerror-return-with-argument-inside-generator](https://stackoverflow.com/questions/15809296/python-syntaxerror-return-with-argument-inside-generator)

**Comment by qhliang** [comment]
you can fix it like below, it works for me.
my pyscreeze version is 0.1.20, edit file pyscreeze/__init__.py, replace "return None" with "return" in line 162 and line 261.

**Comment by lukaszgo1** [comment]
This one seems to be fixed. Can it be closed?

**Comment by jschueller** [comment]
yup
