### ISSUE TITLE
TypeError: '>' not supported between instances of 'float' and 'tuple'

### ISSUE THREAD

**Issue by masterkain** [asweigart/pyscreeze#90]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/kain/src/parser/main.py", line 36, in run
    spell_scan_result = pyautogui.locateOnScreen(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyautogui/__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyautogui/__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyscreeze/__init__.py", line 381, in locateOnScreen
    if retVal or time.time() - start > minSearchTime:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'float' and 'tuple'
```

**Comment by masterkain** [comment]
my bad, passing wrong params
